-- Durable session state, so AudioMind survives a Railway redeploy.
--
-- WHY THIS TABLE EXISTS
-- Sessions lived in `uploads/sessions.json`, mirrored from an in-memory dict.
-- Railway Free has no persistent volume, so that file vanished on every
-- redeploy. The audio was already durable in Cloudflare R2 (§3.1.2, §3.2.1),
-- but the POINTERS to it were not: a user reloading after a deploy got
-- "session not found" and had to re-upload from scratch. This table moves the
-- session record into Postgres so the pointers survive the process that
-- created them.
--
-- SCOPE / SAFETY
-- Purely additive, mirroring 20260930183000_create_dsp_jobs.sql: ONE new table,
-- nothing else referenced. `tracks`, `masters`, `track_events`, `profiles`,
-- `role_audit_logs` and the `audio-originals` / `audio-masters` buckets are
-- untouched.
--
-- NO BACKFILL, DELIBERATELY
-- The MVP does not migrate existing `sessions.json` rows. They are throwaway
-- demo sessions with no user value, and a backfill would add a one-shot
-- migration path that must then be kept correct forever. Enabling the backend
-- is a clean break: anything created before the switch is simply gone.
--
-- WHO CAN READ IT
-- RLS is enabled with NO policies. That is deliberate:
--   - the backend authenticates with the Supabase *service_role* key, which
--     bypasses RLS, so `SupabaseSessionBackend` keeps working;
--   - the browser never touches this table -- Studio talks to our FastAPI.
-- So the anon/authenticated roles get zero access. Do not add a permissive
-- policy: session rows carry R2 keys and full analysis payloads, and the
-- download URL is signed server-side for that reason.

create table if not exists public.sessions (
    -- Opaque id generated by the app (uuid4 hex), never by the DB.
    session_id text primary key,

    -- Mirrors the Python `ProcessingStatus` StrEnum. CHECKed so a typo can
    -- never become a status the client cannot classify.
    status text not null default 'uploaded'
        check (status in ('uploaded', 'analyzing', 'processing',
                          'completed', 'error')),

    -- The complete SessionData, exactly as `model_dump(mode="json")` emits it.
    --
    -- WHY ONE jsonb AND NOT A COLUMN PER FIELD: SessionData is a Pydantic model
    -- with nested models (AnalysisResult, MasteringReport, ValidationReport,
    -- PresetMasterEntry), enums and free-form dicts. Mirroring it into columns
    -- means a migration every time the DSP adds a metric, and a
    -- column-per-field upsert silently DROPS the keys Postgres does not know
    -- -- losing analysis data with no error raised anywhere. The payload is the
    -- single source of truth; `status` above is extracted only because it is
    -- worth indexing.
    --
    -- mode="json" already renders enums as strings and datetimes as ISO-8601,
    -- so this round-trips through `model_validate` with no custom codec.
    payload jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

comment on table public.sessions is
    'Durable AudioMind session state. Read/written by AudioMind with the service_role key.';
comment on column public.sessions.payload is
    'Verbatim SessionData.model_dump(mode="json"). Single source of truth; the status column is a queryable extract, not a copy to keep in sync.';

-- Bounded sweep for the TTL janitor. `demo_guard.prune_expired_sessions` only
-- ever sees the in-memory dict, which is empty on a cold start -- so a session
-- that was never re-read in this process is invisible to it, and the DB needs
-- its own aging index.
create index if not exists sessions_updated_at_idx
    on public.sessions (updated_at desc);

-- Housekeeping. The app never deletes rows on its own, so this grows one row
-- per session. A session idle for days carries no value: its audio lives in R2
-- under its own lifecycle. NOT enabled by this migration on purpose, same
-- reasoning as dsp_jobs: pg_cron is an extension that has to be turned on per
-- project, and surprising a project with a background writer is not this
-- migration's call.
--
--   delete from public.sessions
--    where updated_at < now() - interval '7 days';

-- RLS on, zero policies: service_role bypasses it, anon/authenticated get
-- nothing. See the header note before adding a policy.
alter table public.sessions enable row level security;