-- Multi-tenant "project document" schema (Moises-style).
--
-- WHY THIS EXISTS
-- The backend today is anonymous and session-scoped: audio is keyed by an
-- in-memory ``session_id`` gated only by a license key, mixes do not persist,
-- and stems are served off the ephemeral container disk. This migration turns
-- that into a per-user document model:
--
--   * ``projects``      — one row per user project (name, bpm, musical key).
--   * ``audio_assets``  — every file belonging to a project (the uploaded
--                         original, each separated stem, each master), with a
--                         deterministic R2 key and an optional ``media_hash``.
--   * ``project_states``— the live mix state as JSONB (faders, pan, undo/redo)
--                         so a reload restores the exact mix.
--
-- ``dsp_jobs`` (the existing durable job table) is deliberately NOT altered
-- here. The async separation job reuses it as-is and stores its per-job
-- context (``user_id``, ``project_id``, ``media_hash``, ``asset_id``) in the
-- ``meta`` jsonb column it already has — the same way the mastering job stores
-- ``meta={"track_id": ...}``. That keeps one job table and one job vocabulary.
--
-- ROW LEVEL SECURITY
-- Unlike ``dsp_jobs``/``sessions`` (backend-only, service_role, zero policies),
-- these three tables are ALSO read and written directly by the authenticated
-- Studio client. So each carries a real policy ``auth.uid() = user_id``. The
-- backend still writes with service_role (which bypasses RLS) for background
-- work, but the browser path is fenced per user by Postgres itself.
--
-- SAFE TO RUN MORE THAN ONCE
-- Every statement is guarded (``if not exists`` / drop-then-create policy).
-- The dashboard is the real deploy path here, so a double paste must be a
-- no-op, not a crash.

-- ── Part 1: projects ───────────────────────────────────────────────────────

create table if not exists public.projects (
    -- Generated by Postgres; the app never invents this id.
    id uuid primary key default gen_random_uuid(),

    -- Owner. ON DELETE CASCADE so removing a user removes their projects (and,
    -- transitively, their assets and states via the FKs below).
    user_id uuid not null references auth.users (id) on delete cascade,

    -- Human label shown in the library. Not unique on purpose: two projects
    -- may share a name; ``id`` is the identity.
    name text not null default 'Untitled project',

    -- Musical metadata, nullable: a project may be created before analysis.
    bpm integer,
    musical_key text,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

comment on table public.projects is
    'One user project (the Moises-style document root). RLS-fenced by user_id.';
comment on column public.projects.user_id is
    'Owner in auth.users. RLS predicate is auth.uid() = user_id.';

-- The library list orders by recency for a single user; this keeps it off a
-- sequential scan as the table grows.
create index if not exists projects_user_id_updated_at_idx
    on public.projects (user_id, updated_at desc);

alter table public.projects enable row level security;

-- Drop-then-create keeps a re-paste idempotent (Postgres has no
-- ``create policy if not exists`` before v15, and the dashboard is v14+).
drop policy if exists "projects_select_own" on public.projects;
create policy "projects_select_own"
    on public.projects for select
    using (auth.uid() = user_id);

drop policy if exists "projects_insert_own" on public.projects;
create policy "projects_insert_own"
    on public.projects for insert
    with check (auth.uid() = user_id);

drop policy if exists "projects_update_own" on public.projects;
create policy "projects_update_own"
    on public.projects for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "projects_delete_own" on public.projects;
create policy "projects_delete_own"
    on public.projects for delete
    using (auth.uid() = user_id);

-- ── Part 2: audio_assets ───────────────────────────────────────────────────

create table if not exists public.audio_assets (
    id uuid primary key default gen_random_uuid(),

    -- Owning project. ON DELETE CASCADE: deleting a project removes its files'
    -- bookkeeping (the R2 objects themselves are reclaimed by a separate
    -- lifecycle, not by this FK).
    project_id uuid not null references public.projects (id) on delete cascade,

    -- Denormalized owner so the RLS predicate needs no join and a background
    -- job can be filtered by user without resolving the project first.
    user_id uuid not null references auth.users (id) on delete cascade,

    -- What this asset IS. CHECKed so a typo cannot become a kind the frontend
    -- cannot classify.
    kind text not null
        check (kind in ('original', 'stem', 'master')),

    -- Only meaningful when kind = 'stem' (drums|bass|other|vocals). NULL for
    -- originals and masters. Not FK'd to an enum: the stem vocabulary lives in
    -- the backend (processing.splitter.STEM_NAMES) and mirrors here as text.
    stem_name text,

    -- Stable Cloudflare R2 object key. The presigned download URL is minted on
    -- demand (it expires); this key is the durable pointer and is what the
    -- backend re-signs on every read.
    r2_key text not null,

    -- SHA-256 of the audio bytes. NULL until computed (originals get it when
    -- the browser reports it on upload, or when separation runs). This is the
    -- idempotency key: separating the same bytes twice must not re-run Demucs.
    media_hash text,

    -- Introspection captured at upload time (frontend Web Audio decode, or the
    -- separation result for stems). All nullable: a register can precede a
    -- full probe.
    original_filename text,
    duration_seconds real,
    sample_rate integer,
    channels integer,
    format text,
    size_bytes bigint,

    created_at timestamptz not null default now()
);

comment on table public.audio_assets is
    'Files belonging to a project (original, stems, masters) as durable R2 keys. RLS-fenced by user_id.';
comment on column public.audio_assets.media_hash is
    'SHA-256 of the bytes; idempotency key for stem separation. NULL until computed.';
comment on column public.audio_assets.r2_key is
    'Durable R2 object key. Presigned URLs are minted on demand and expire; this does not.';

-- Project library view: list a project's files, newest first.
create index if not exists audio_assets_project_id_created_at_idx
    on public.audio_assets (project_id, created_at desc);

-- Idempotency lookup: "is there a stem for these bytes?" scans by user + hash.
-- Partial so it stays tiny (most assets have no hash yet).
create index if not exists audio_assets_user_media_hash_idx
    on public.audio_assets (user_id, media_hash)
    where media_hash is not null;

alter table public.audio_assets enable row level security;

drop policy if exists "audio_assets_select_own" on public.audio_assets;
create policy "audio_assets_select_own"
    on public.audio_assets for select
    using (auth.uid() = user_id);

drop policy if exists "audio_assets_insert_own" on public.audio_assets;
create policy "audio_assets_insert_own"
    on public.audio_assets for insert
    with check (auth.uid() = user_id);

drop policy if exists "audio_assets_update_own" on public.audio_assets;
create policy "audio_assets_update_own"
    on public.audio_assets for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "audio_assets_delete_own" on public.audio_assets;
create policy "audio_assets_delete_own"
    on public.audio_assets for delete
    using (auth.uid() = user_id);

-- ── Part 3: project_states ─────────────────────────────────────────────────
-- One row per project (PK is project_id), holding the live mix as JSONB.

create table if not exists public.project_states (
    -- 1:1 with projects. The PK is load-bearing, not decoration: the autosave
    -- PATCH upserts on it, so Postgres resolves the conflict target here.
    project_id uuid primary key references public.projects (id) on delete cascade,

    -- Denormalized owner for a join-free RLS predicate.
    user_id uuid not null references auth.users (id) on delete cascade,

    -- The mix document: per-stem gain/pan, master fader, any UI the frontend
    -- needs to restore. JSONB rather than a column per knob: the shape is owned
    -- by the frontend and will evolve; a column-per-field upsert would silently
    -- drop keys Postgres does not know about.
    state jsonb not null default '{}'::jsonb,

    -- Undo/redo history as an array of prior ``state`` snapshots. Bounded in
    -- the application (the backend/frontend cap its length), not here.
    undo_stack jsonb not null default '[]'::jsonb,

    updated_at timestamptz not null default now()
);

comment on table public.project_states is
    'Live mix state per project (faders, pan, undo/redo) as JSONB. RLS-fenced by user_id.';
comment on column public.project_states.state is
    'Frontend-owned mix document; shape evolves with the Studio, so it stays JSONB.';
comment on column public.project_states.undo_stack is
    'Array of prior state snapshots for undo/redo; length capped in the app.';

alter table public.project_states enable row level security;

drop policy if exists "project_states_select_own" on public.project_states;
create policy "project_states_select_own"
    on public.project_states for select
    using (auth.uid() = user_id);

drop policy if exists "project_states_insert_own" on public.project_states;
create policy "project_states_insert_own"
    on public.project_states for insert
    with check (auth.uid() = user_id);

drop policy if exists "project_states_update_own" on public.project_states;
create policy "project_states_update_own"
    on public.project_states for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "project_states_delete_own" on public.project_states;
create policy "project_states_delete_own"
    on public.project_states for delete
    using (auth.uid() = user_id);
